name: Issue Auto Labeling

on:
  issues:
    types: [opened, edited]

jobs:
  label-and-assign:
    runs-on: ubuntu-latest
    steps:
      - name: 자동 라벨링
        uses: github/issue-labeler@v3.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          enable-versioned-regex: false
